# Generated by Django 4.2.23 on 2025-07-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('characters', models.CharField(max_length=200)),
                ('moral', models.CharField(max_length=200)),
                ('content', models.TextField(default='Once upon a time...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
