# Generated by Django 4.2.23 on 2025-07-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_storyrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyrevision',
            name='revision_applied',
            field=models.BooleanField(default=False),
        ),
    ]
