# Generated by Django 5.2.4 on 2025-08-07 06:47

import django.db.models.deletion
import story.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_story_user_alter_storyrevision_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('image', models.ImageField(upload_to=story.models.story_image_upload_path)),
                ('style', models.CharField(default='default', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='story.story')),
            ],
        ),
    ]
