# Generated by Django 5.2.4 on 2025-08-12 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('math', 'Math'), ('science', 'Science'), ('english', 'English'), ('gk', 'General Knowledge')], max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('worksheet_type', models.CharField(choices=[('quiz', 'Quiz'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('crossword', 'Crossword'), ('mixed', 'Mixed')], max_length=50)),
                ('content', models.JSONField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='worksheets/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorksheetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='worksheets/images/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wimages', to='worksheet_generator.worksheet')),
            ],
        ),
    ]
